[PS-1402] New RealPage Api
netvendor2017/intacct-sdk-php pull request #1
Opened 2024-02-20 16:20 UTC by JaredCowan

Silence is golden

2024-02-20 16:50 UTC, adam-winfree commented on .gitignore
> +.DS_Store
I just put this in my global `.gitignore` but I can see the value of having it here.

2024-02-20 17:40 UTC, VirgilAnderson commented on src/Intacct/ClientConfig.php
> +    public function setHeaders(array $headers)
return type?

2024-02-20 17:40 UTC, VirgilAnderson commented on src/Intacct/ClientConfig.php
> +    public function addHeader(string $key, string $value)
return type

2024-02-20 17:41 UTC, VirgilAnderson commented on src/Intacct/Functions/AccountsPayable/AbstractVendor.php
> +    public function setRestrictionType(string $restrictionType)
return types here too?

2024-02-20 17:41 UTC, VirgilAnderson commented on src/Intacct/Functions/AccountsPayable/AbstractVendor.php
> +            if (!isset($vendorDesignation['name'])) {
```suggestion
            if (! isset($vendorDesignation['name'])) {
```

2024-02-20 17:41 UTC, VirgilAnderson commented on src/Intacct/Functions/AccountsPayable/AbstractVendor.php
> +        if (!isset($vendorDesignation['name'])) {
```suggestion
        if (! isset($vendorDesignation['name'])) {
```

2024-02-20 17:42 UTC, VirgilAnderson commented on src/Intacct/Functions/AccountsPayable/AbstractVendor.php
> +    public function getInsuranceRequired() {
return types

2024-02-20 17:42 UTC, VirgilAnderson commented on src/Intacct/Functions/AccountsPayable/VendorCreate.php
> +        if (!empty($this->getRestrictedLocations())) {
```suggestion
        if (! empty($this->getRestrictedLocations())) {
```

2024-02-20 17:43 UTC, VirgilAnderson commented on src/Intacct/Functions/AccountsPayable/VendorCreate.php
> +        if (!empty($this->getCustomFieldsV2())) {
```suggestion
        if (! empty($this->getCustomFieldsV2())) {
```

2024-02-20 17:43 UTC, VirgilAnderson commented on src/Intacct/Functions/AccountsPayable/VendorUpdate.php
> +        if (!empty($this->getRestrictedLocations())) {
```suggestion
        if (! empty($this->getRestrictedLocations())) {
```

2024-02-20 17:43 UTC, VirgilAnderson commented on src/Intacct/Functions/AccountsPayable/VendorUpdate.php
> +        if (!empty($this->getCustomFieldsV2())) {
```suggestion
        if (! empty($this->getCustomFieldsV2())) {
```

2024-02-20 17:43 UTC, VirgilAnderson commented on src/Intacct/Functions/Traits/CustomFieldsV2Trait.php
> +    public function getCustomFieldsV2(): array
```suggestion
    public function getCustomFieldsV2() : array
```

2024-02-20 17:43 UTC, VirgilAnderson commented on src/Intacct/Functions/Traits/CustomFieldsV2Trait.php
> +    public function setCustomFieldsV2(array $customFields)
return types

2024-02-20 17:44 UTC, VirgilAnderson reviewed
Couple little things

2024-02-20 17:50 UTC, JaredCowan commented on .gitignore
> +.DS_Store
Not a big fan of globals because you need to assume everyone has what you have.

2024-02-20 17:58 UTC, adam-winfree requested changes
I have no idea how RealPage works, so my thoughts are pretty simple.

2024-02-20 17:58 UTC, adam-winfree commented on src/Intacct/ClientConfig.php
> +
I've never thought that null could be a key. It looks like it would be cast to an empty string like you have here. https://www.php.net/manual/en/language.types.array.php#language.types.array.key-casts

If that's the case, you could shorten this to `$headerKeys = array_map('strtolower', array_keys($this->headers));`

2024-02-20 17:58 UTC, adam-winfree commented on src/Intacct/ClientConfig.php
> +        return ! empty($this->headers) && array_key_exists('apikey', $headerKeys);
It seems like this could just be `in_array('apikey', $headerKeys)` or `array_key_exists('apikey', $headerKeys)`. It's not empty if it has the `apikey` key.

2024-02-20 17:58 UTC, adam-winfree commented on .gitignore
> +.DS_Store
Are you kidding? Everyone should have what I have 😄

2024-02-20 17:58 UTC, adam-winfree commented on src/Intacct/Functions/AccountsPayable/AbstractVendor.php
> +     * @var
I'm just a var, take a good look at me. Just your typical prototype.

2024-02-20 17:58 UTC, adam-winfree commented on src/Intacct/Functions/AccountsPayable/AbstractVendor.php
> +    public function getInsuranceRequired() {
And the bracket should be on the new line. Same for below

2024-02-23 02:32 UTC, lancepioch commented on src/Intacct/ClientConfig.php
> +     */
```suggestion
    public function getHeaders() : ?array
    {
        return $this->headers;
    }

    public function setHeaders(array $headers) : void
    {
        $this->headers = $headers;
    }

```

Don't need docblocks!

2024-02-23 02:32 UTC, lancepioch commented on src/Intacct/Functions/AccountsPayable/AbstractVendor.php
> +     */
I don't think these do anything but take up space?

2024-05-04 23:34 UTC, dhazelett approved these changes

2024-05-22 16:47 UTC, closed without merging